# Generated by Django 5.2.17 on 2026-09-15 18:22

from django.db import migrations


def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    items = []
    for item in OrderItem.objects.filter(price__isnull=True).select_related('product'):
        item.price = item.product.price
        items.append(item)
    OrderItem.objects.bulk_update(items, ['price'])


def unfill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    OrderItem.objects.update(price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_prices, unfill_prices),
    ]