# Generated by Django 5.2.17 on 2026-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='комментарий'),
        ),
    ]
