# Generated by Django 5.2.17 on 2026-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('online', 'Электронно'), ('cash', 'Наличными при доставке')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
