# Generated by Django 5.2.17 on 2026-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('online', 'Электронно'), ('cash', 'Наличными при доставке')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
